import './css/globals.css'
import type { Metadata } from 'next'
import Header from './components/header/header'
import Footer from './components/footer/footer'
import ReduxProvider from './components/store/reduxProvider'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
